[package]
name = "c2r"
description = "A C to Rust conversion program"
repository = "https://github.com/nullorigin/c2r.git"
license = "MIT"
authors = ["Matthew Fay"]
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "c2r"
path = "src/main.rs"