[package]
name = "c2rs"
description = "A C to Rust conversion program"
repository = "https://github.com/nullorigin/c2rs.git"
license = "MIT"
authors = ["Matthew Fay"]
version = "0.1.0"
edition = "2024"

[dependencies]
